server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/riskdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  flyway:
    enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: admin
    password: admin
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  security:
    user:
      name: admin
      password: admin

management:
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
  secret: "mysupersecretkeymysupersecretkey12345"
  expiration: 86400000